# Generated by Django 3.2.10 on 2022-01-11 06:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('picture_url', models.URLField()),
                ('presentation_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(default=website.models.reservation.generate_access_code, max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('max_guests', models.IntegerField(default=2)),
                ('rsvp_updated_at', models.DateTimeField()),
                ('mailing_address_line_1', models.CharField(blank=True, max_length=200)),
                ('mailing_address_line_2', models.CharField(blank=True, max_length=200)),
                ('mailing_address_city', models.CharField(blank=True, max_length=200)),
                ('mailing_address_state', models.CharField(blank=True, max_length=2)),
                ('mailing_address_zip', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('rsvp_answer', models.BooleanField(default=None)),
                ('rsvp_comment', models.CharField(blank=True, max_length=1000)),
                ('assigned_table', models.IntegerField(blank=True)),
                ('assigned_table_seat', models.IntegerField(blank=True)),
                ('food_comment', models.CharField(blank=True, max_length=1000)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('food_selection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.foodoption')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reservation')),
            ],
        ),
    ]
