# Generated by Django 4.0.1 on 2022-03-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='mailing_address_state',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
