# Generated by Django 5.0.1 on 2024-02-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_guest_assigned_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='mailing_address_city',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='mailing_address_line_1',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='mailing_address_line_2',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='mailing_address_state',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='mailing_address_zip',
        ),
    ]
