# Generated by Django 3.2.10 on 2022-01-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220110_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rsvp_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
