# Generated by Django 4.0.1 on 2022-06-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_reservation_mailing_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='attending_ceremony_rehearsal',
            field=models.BooleanField(default=False),
        ),
    ]
