# Generated by Django 4.0.1 on 2022-03-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_emailtemplate_remove_reservation_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='food_selection',
        ),
        migrations.DeleteModel(
            name='FoodOption',
        ),
    ]
