# Generated by Django 4.0.1 on 2022-03-06 06:19

from django.db import migrations, models
import django.utils.timezone
import website.models.email_template


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_guest_food_selection_delete_foodoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='from_email',
            field=models.CharField(default=website.models.email_template.default_from_email, max_length=200),
        ),
        migrations.AlterField(
            model_name='guest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_answer',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='guest',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
