# Generated by Django 4.0.1 on 2022-03-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_emailtemplate_from_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rsvp_answer',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
