# Generated by Django 4.0.1 on 2022-03-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_guest_rsvp_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendgrid_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='sendgrid_subscription_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.emailsubscriptiongroup'),
        ),
    ]
