# Generated by Django 4.0.1 on 2022-03-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_emailsubscriptiongroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kwargs', models.CharField(max_length=1000)),
                ('target_unix_time', models.BigIntegerField()),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='rehearsal_rsvp_answer',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='invited_to_rehearsal',
            field=models.BooleanField(default=False),
        ),
    ]
