# Generated by Django 4.0.1 on 2022-03-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_task_guest_rehearsal_rsvp_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='food_comment',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='hidden',
        ),
    ]
