# Generated by Django 4.0.1 on 2022-03-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_guest_food_comment_remove_guest_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='rsvp_comment',
        ),
        migrations.AddField(
            model_name='guest',
            name='food_vegan_option',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
