# Generated by Django 4.0.1 on 2022-03-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_guest_rsvp_comment_guest_food_vegan_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='food_vegan_option',
            field=models.BooleanField(default=False),
        ),
    ]
